# Draft Configuration
application:
  title: "CCL 2025 Draft"
  logo: "ccl-logo.png"
  background_image: "ccl-background.png"

teams:
  - name: "CHALLENGERS"
    color: "#10b981"  # Brighter green
    captain: "DK"
    pick: 5
  - name: "ALL STARS"
    color: "#facc15"  # Vibrant yellow
    captain: "AJITH"
    pick: 2
  - name: "HAWKS"
    color: "#06b6d4"  # Bright teal
    captain: "BALA"
    pick: 3
  - name: "WARRIORS"
    color: "#8b5cf6"  # Bright purple
    captain: "GIRISH"
    pick: 4
  - name: "KINGS"
    color: "#f97316" # Bright orange
    captain: "ROHAN"
    pick: 6
  - name: "TITANS"
    color: "#3b82f6"  # Bright blue
    captain: "AKSHAY"
    pick: 7
  - name: "SPARTANS"
    color: "#ef4444" # Bright red
    captain: "NIKHIL"
    pick: 1
  
players: # Ideally less than 15 characters
  - "Abdul"
  - "Abey Eapen"
  - "Abhilash"
  - "Ajay Majethia"
  - "Amanpreet Singh"
  - "Antony"
  - "Arslan Bhangu"
  - "Arvind R"
  - "Ashly"
  - "Atul Singh"
  - "Babar Bashir"
  - "Balaji S"
  - "Bhakta"
  - "Bhavadeep"
  - "Brajesh Singh"
  - "Brijesh"
  - "Bunpreet Singh"
  - "Chaitanya T"
  - "Chetan"
  - "Chirag Vijay"
  - "Debashis C"
  - "Dev Bogiatoo"
  - "Dhaval Padia"
  - "Durairaj Kumar"
  - "Elango T"
  - "Eric Sylvester"
  - "Ganesh Koushic"
  - "Gaurav Gaud"
  - "Gopal Kallure"
  - "Govinda Raju"
  - "Gowrishankar S"
  - "Harsha"
  - "Hemin Patel"
  - "Himanshu S"
  - "Ibrahim Khan"
  - "Inderdip Singh"
  - "Jay"
  - "Jitendra Kumar"
  - "Khalil"
  - "Kumar Devasish"
  - "Mahee"
  - "Manivannan K"
  - "Mario Pandian"
  - "Monica Schmidt"
  - "Nadeem"
  - "Nandeesh"
  - "Narendrag"
  - "Naresh K"
  - "Naveen"
  - "Naveen V"
  - "Nirmalraj S"
  - "Nitin Chauhan"
  - "Parin Shah"
  - "Partho BC"
  - "Parvath Reddy"
  - "Pranjal Malav"
  - "Prash"
  - "Prashant P"
  - "Prashanth M"
  - "Raja sekhar"
  - "Rajesh"
  - "Rajkumar M"
  - "Rakesh"
  - "Ramon Howe"
  - "Rehan"
  - "Rohit Jain"
  - "Rohullah M"
  - "Rony"
  - "Sai Vamshi"
  - "Sakhi Rahman"
  - "Sameer T"
  - "Sanath Shetty"
  - "Sandeep C"
  - "Sateesh"
  - "Satya T"
  - "Shaizullah M"
  - "Sikandar AD"
  - "Simranjeet S"
  - "Siva K"
  - "Subhashish C"
  - "Sudin Huddar"
  - "Vaidya TR"
  - "Venkatraman K"
  - "Vignesh R"
  - "Vignesh SR"
  - "Vijay Ramesh"
  - "Vikas Kalia"
  - "Vishal C"
  - "Yasar Ijaz"
  - "Yashas Reddy"
  - "Yuva Raju C"
  - "Krishna"
  - "Saipreetham"
