# CCL Draft Configuration
application:
  title: "CCL 2025 Draft"
  logo: "ccl-logo.png"
  background_image: "ccl-background.png"

teams:
  - name: "CHALLENGERS"
    color: "#10b981"  # Brighter green
    captain: "DK"
    pick: 2  # First pick
  - name: "ALL STARS"
    color: "#facc15"  # Vibrant yellow
    captain: "AJITH"
    pick: 1  # Second pick
  - name: "HAWKS"
    color: "#06b6d4"  # Bright teal
    captain: "BALA"
    pick: 3  # Third pick
  - name: "WARRIORS"
    color: "#8b5cf6"  # Bright purple
    captain: "GIRISH"
    pick: 4  # Fourth pick
  - name: "KINGS"
    color: "#f97316"  # Bright orange
    captain: "ROHAN"
    pick: 5  # Fifth pick
  - name: "TITANS"
    color: "#3b82f6"  # Bright blue
    captain: "AKSHAY"
    pick: 6  # Sixth pick
  - name: "SPARTANS"
    color: "#ef4444"  # Bright red
    captain: "NIKHIL"
    pick: 7  # Seventh pick

draft:
  rounds: 14  # Number of rounds excluding captains
  
players:
  - "Himanshu"
  - "Raj"
  - "Akhil"
  - "Anish"
  - "Rohit"
  - "Arun"
  - "Gokul"
  - "Adarsh"
  - "Rahul"
  - "Vivek"
  - "Pranav"
  - "Vijay"
  - "Shiva"
  - "Nitin"
  - "Karthik"
  - "Sachin"
  - "Saurav"
  - "Shyam"
  - "Vinay"
  - "Lokesh"
  - "Manoj"
  - "Praveen"
  - "Raghu"
  - "Ravish"
  - "Varun"
  - "Sriram"
  - "Sujith"
  - "Sunil"
  - "Shashank"
  - "Arjun"
  - "Deepak"
  - "Harish"
  - "Prithvi"
  - "Naveen"
  - "Uday"
  - "Vishnu"
  - "Vasu"
  - "Dhruv"
  - "Krishna"
  - "Mohan"
  - "Gopal"
  - "Jitesh"
  - "Santosh"
  - "Subhash"
  - "Chetan"
  - "Nithin"
  - "Gautam"
  - "Manu"
  - "Chandra"
  - "Baskar"
  - "Vikram"
  - "Ramesh"
  - "Sudhir"
  - "Kiran"
  - "Bharat"
  - "Ganesh"
  - "Jayesh"
  - "Dinesh"
  - "Ishaan"
  - "Kamal"
  - "Mahesh"
  - "Naresh"
  - "Prakash"
  - "Prem"
  - "Shankar"
  - "Tarun"
  - "Vishal"
  - "Vimal"
  - "Aditya"
  - "Aravind"
  - "Hari"
  - "Kunal"
  - "Mukesh"
  - "Naren"
  - "Ritesh"
  - "Sagar"
  - "Sameer"
  - "Tejas"
  - "Umesh"
  - "Venkat"
  - "Yash"
  - "Zubin"
  - "Abhinav"
  - "Balaji"
  - "Chirag"
  - "Darshan"
  - "Farhan"
  - "Girish"
  - "Hiten"
  - "Irfan"
  - "Jeevan"
  - "Keshav"
  - "Lalit"
  - "Mayank"
  - "Nikhil"
  - "Omkar"
  - "Pradeep"
